### ISSUE TITLE
We really should handle new line in exception message !!

### ISSUE THREAD

**Issue by Geolim4** [filp/whoops#298]
Hi,

Because any html string will be shown as plain text, we should take care of new line "\n" in exception message.

I can provide a quickfix for that.

**Comment by GrahamCampbell** [comment]
Why would an exception have a newline in it?

**Comment by staabm** [comment]
Same question here: I dont think a newline should be contained in a Exception message.

**Comment by Geolim4** [comment]
Not in my case, i have already seen some libs using (invisible) new line. And it allow a minimal text formating for very long exception messages, allowing a more readable exception (IMO).

**Comment by staabm** [comment]
IMO the pretty page handler should format via css when lines break

**Comment by Geolim4** [comment]
Yes, but the point is also to take care of Exception-generated line-break :)

**Comment by staabm** [comment]
I get what you are saying. IMO a exception message shouldn't contain a line-break.

**Comment by GrahamCampbell** [comment]
> IMO a exception message shouldn't contain a line-break.

Yeh, I totally agree.

**Comment by Petah** [comment]
We don't control what an exception message contains, such as from a library, so if it is preformatted it would be nice to render it so.

**Comment by GrahamCampbell** [comment]
> such as from a library

Send a PR to that library and get it changed.

**Comment by Petah** [comment]
Apart from being purest, is there any real down side to running a simple `nl2br` or `white-space: pre` over the message?

My use case is an API error gets converted to an exception which contains long verbose information:

```
Invalid HMAC-SHA1 signature. 
Base string: GET&https%3A%2F%2Fapi.com%2Fv1%2FSearch%2FGeneral.json&category%3D0187-0442-%26oauth_consumer_key%3DEC7D575D42C6F62B171C8CF3FA2DFD80%26oauth_nonce%3D55a504ce19076%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1436878030%26oauth_version%3D1.0%26rows%3D500 
Request: https://api.com/v1/Search/General.json?category=0187-0442-&oauth_consumer_key=EC7D575D42C6F62B171C8CF3FA2DFD80&oauth_nonce=55a504ce19076&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1436878030&oauth_version=1.0&rows=500&oauth_signature=7tLSsFHxndoV6R4ISIs8BBooQaA=
```

Which is much easier to seperate the 2 key parts of the execption compared to 

`Invalid HMAC-SHA1 signature. Base string: GET&https%3A%2F%2Fapi.com%2Fv1%2FSearch%2FGeneral.json&category%3D0187-0442-%26oauth_consumer_key%3DEC7D575D42C6F62B171C8CF3FA2DFD80%26oauth_nonce%3D55a504ce19076%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1436878030%26oauth_version%3D1.0%26rows%3D500 Request: https://api.com/v1/Search/General.json?category=0187-0442-&oauth_consumer_key=EC7D575D42C6F62B171C8CF3FA2DFD80&oauth_nonce=55a504ce19076&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1436878030&oauth_version=1.0&rows=500&oauth_signature=7tLSsFHxndoV6R4ISIs8BBooQaA=`

**Comment by Geolim4** [comment]
> Apart from being purest, is there any real down side to running a simple
Well said, but it's tiring to debate alone just for trying to justify why doing something better.

**Comment by denis-sokolov** [comment]
I am practical, and although I value purity in discussions, I will choose a pragmatic solution for a widely-used library such as Whoops.

However, treating newlines in the exception messages as meaningful has a considerable danger of breaking the layout for messages that today have many newlines in them already.
Consider a case where a message is generated by extracting it from an element on an HTML page. It is likely the element contains a lot of whitespace that the users never noticed because we implicitly collapse that whitespace.

Although there is no standard or guide on what PHP exception messages should look like, the default behavior PHP exception handler will also collapse the whitespace, even though it will add `<b>` to the header:
```
<b>FATAL ERROR</b> Uncaught exception 'Exception' with message 'Hello,
world!' in foo.php(5) : eval()'d code:2
Stack trace:
#0 foo.php(5): eval()
#1 {main}
  thrown on line number 2
```

This handler has many problems, but the main lesson is - people expect to have their whitespace collapsed in PHP error handling. And if they don't have Whoops, they're not in a better position.

**Comment by Petah** [comment]
Well you could handle that easily with an `overflow-y: scroll` and a
`max-height`. (just expressing my thoughts, not trying to start a war :)

I think it would be more reasonable to open a PR on a library if their
exceptions were creating too many newlines rather that the opposite.

**Comment by Petah** [comment]
Well you could handle that easily with an `overflow-y: scroll` and a
`max-height`. (just expressing my thoughts, not trying to start a war :)

I think it would be more reasonable to open a PR on a library if their
exceptions were creating too many newlines rather that the opposite.

**Comment by denis-sokolov** [comment]
> Well you could handle that easily with an `overflow-y: scroll` and a `max-height`.

I am less concerned about breaking the layout and more concerned that users who used to see their exception message will now see an empty line with a scrollbar and the message way down below, because the message was prefixed with 5 newlines.

> I think it would be more reasonable to open a PR on a library if their exceptions were creating too many newlines rather that the opposite.

I do not disagree.
The crucial distinction is you propose to change the current behavior.
That is suddenly and unexpectedly harm an unknown amount of users.
The alternative is to not provide a new feature for a definitely small number of users (2 so far).
I'm sorry, but the pragmatic choice here is to not change anything.

**Comment by Petah** [comment]
Fair enough.

So when are we going to start working on Whoops 2.0?

**Comment by denis-sokolov** [comment]
Backwards-incompatible changes are not great, so ideally never. :) 
I assume you ask this question in the context of making the change to how we display an exception message. That's not a change that would make us bump a major number.
