### ISSUE TITLE
PHP7 Errors are not properly handled

### ISSUE THREAD

**Issue by moay** [filp/whoops#341]
I just tested out v2 with PHP7, which works really great. There was only one problem: PHP7 doesn't any more handle all Errors as errors, most of the are a new thing between Error and Exception. See: http://php.net/manual/de/language.errors.php7.php

Currently, those new Errors will be handled by Whoops' ExceptionHandler, which expects Exceptions and therefore throws an Error telling me that the Exception is not an Exception.

**Comment by mahagr** [comment]
Uncaught TypeError: Argument 1 passed to Whoops\Run::handleException() must be an instance of Exception, instance of Error given in vendor\filp\whoops\src\Whoops\Run.php:234

As `Error` class extends `Throwable` (also new in PHP7), type hinting should be removed from the function in order to make it to work.

**Comment by staabm** [comment]
will be fixed by https://github.com/filp/whoops/pull/284

**Comment by denis-sokolov** [comment]
Indeed, we're in the transitional period and we need to release version 2 quickly.
Watch #284 or the releases list.
