### ISSUE TITLE
[css] Increase header max-height

### ISSUE THREAD

**Issue by mikerockett** [filp/whoops#358]
On a standard 16x9/1366 display, the `<header>` element expands on hover when there are four lines of text in `p.exc-message`.

To resolve, the `<header>`'s `max-height` should be 200px.

**Comment by denis-sokolov** [comment]
Why is it bad to have a high header if, indeed, the message is so long?

**Comment by mikerockett** [comment]
Busy upgrading my server, so can't do a screen-cast of what actually happens. On Firefox, hovering over the header that contains four lines of text essentially 'increases the padding', if you will, of the header itself. So the text remains in place, but the actualy dark header area grows.

**Comment by mikerockett** [comment]
Up and running again - here's a GIF: http://g.recordit.co/E0LizFc2T3.gif

**Comment by denis-sokolov** [comment]
Alright, I see what you mean. Thank you for your report.

Unfortunately, changing the max-height to 200px will not fix anything - the height of the text is not fixed and if it happens to work for you with 200px it might not for others with other OS/browser/font settings.
If anyone cares to propose a proper fix, great. But currently I will choose to treat this as a unlucky minor details specific to a particular window configuration.

**Comment by mikerockett** [comment]
I don't understand - the `font-*` are preset by the stylesheet, so I don't see how it would look radically different between others' browsers.

If anything, this is indeed super irritating, at least for me. My current work-around is to increase the max height and reduce the text size.

Btw: I don't actually fully understand why a max height has even been implemented... it makes no sens at all to me. Kindly clarify?

**Comment by denis-sokolov** [comment]
Font rendering depends on a multitude of factors - whether or not the user has the font, is it the right font, what is the user's font rendering subsystem in the OS, whether the user has a minimal font size set, whether manually or by browser vendor's choice, whether the user used a zoom function or not, and so on. Point is, we can't know how high it should be.

I suppose the original premise behind a max-height was so that a very long message would not push the entire page. I would accept a change to use `text-overflow` instead. That should fix your problem if we `ellipsis` by default and reveal on hover.

**Comment by mikerockett** [comment]
Right, makes sense.

Hopefully this wouldn't make the interface seem to complex, but perhaps the area should fade the long text out at a certain height to show that there's more, and then a simply arrow to the right to expand and then collapse. Problem with the hovering effect is that when I move the mouse over the area to get to the back button, it quickly expands and collapses, which is quite annoying.
