### ISSUE TITLE
Inverted syntax coloration for comments and code

### ISSUE THREAD

**Issue by Litarvan** [filp/whoops#426]
The code syntax coloration is inverted. Code is considered as comment, and comment as code. Only when there is doc comment before. It does not happen everytime but often.

![Screen](https://i.gyazo.com/7f5830a871cc95faf7578c485548239b.png)

Some informations : 

SERVER_SOFTWARE "PHP 5.6.8 Development Server"
SERVER_PROTOCOL "HTTP/1.1"
SERVER_NAME "localhost"
SERVER_PORT "58777"
REQUEST_URI "/test"
REQUEST_METHOD "GET"
SCRIPT_NAME "/index.php
HTTP_HOST "localhost:58777"
HTTP_USER_AGENT "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0"

**Comment by denis-sokolov** [comment]
Thank you for your report. We have already discussed this in #214, and, since there is no easy obvious fix, and the impact of the bug is small, we have decided to not do anything about it. If anyone has motivation to fix this, a PR is most welcome. Otherwise, this will be a small quirk in Whoops for a while. :)

**Comment by Litarvan** [comment]
Ok thanks, maybe I will send a post request ^^
