### ISSUE TITLE
How to get the "edit in editor" to map the file path to a local resource

### ISSUE THREAD

**Issue by dtunes** [filp/whoops#440]
I'm using Homestead, setting the editor to sublime works, except that the path returned is also on the VM /home/vagrant/Code/someapp/test.php, subl://open?url=file://%2Fhome%2Fvagrant%2FCode%2Fsomeapp%2Ftest.php&line=6, how would I go about overriding the path to the file?
e.g. 
/home/vagrant/Code/someapp/test.php
to return
/$HOME/Code/someapp/test.php
I had a look on PrettyPageHandler.php but couldn't find a method to set the path, maybe I didn't know exactly what to look for. Has anyone come across this and if you solved it, could you share your solution?

**Comment by acidjazz** [comment]
@dtunes I would create and symlink /whatever/vagrant/folders to your localized version using ln -s.

```bash
mkdir /home; mkdir /home/vagrant; mkdir /home/vagrant/Code;

ln -s ~/Code/someapp /home/vagrant/Code/someapp
```

I might have the ln -s parameters backwords

**Comment by dtunes** [comment]
I see, didn't think of something so simple. Will try it tomorrow. Cheers

**Comment by dtunes** [comment]
Would be better thou to be able to overwrite that in a setting somehow.

**Comment by denis-sokolov** [comment]
I am happy there is an easy solution for now. We will see how requested this feature is in the future.

**Comment by jbbr** [comment]
+1 for this feature.
"Jump to source" is a nice thing but without path mapping it's unusable with remote environments using Docker, Vagrant, ...

Mapping could be as easy as a having a simple `from->to` array like:

```php
$handler->setPathMapping([
    '/var/www' => '/home/user/dev/project/src'
]);
```
This would only require a search and replace when building the urls for the editor.

**Comment by SvenRtbg** [comment]
Please consider that the path mapping on the server will likely not match every client layout. Of course you can make it so that you run your own server, and define your own mapping, independent from anyone else - but committing this mapping into the project would be forcing it onto others with a different setup. It may be a nice feature, but requires a local configuration.

**Comment by jbbr** [comment]
@SvenRtbg Of course hardcoding the mapping is not an option. This would always require local configuration.
The actual mapping could be read from some .env file or whatever your project is using for configuration overrides. Whoops just have to provide the API for defining those mappings.

**Comment by denis-sokolov** [comment]
The idea is it’s hardcoded on your server, whereas your developers can have different setups. What’s “/home/www” on your machine can be “c:\httpd\” on mine.

**Comment by githubjeka** [comment]
Nothing has changed since then?

**Comment by ddanielou** [comment]
Respectfully, I think this issue should be reopened.

We're in the midst of switching from Ignition (whose destiny is uncertain) to whoops, and [this is possible in Ignition](https://github.com/spatie/ignition/issues/114).

It's pretty simple to create a custom editor, e.g. for IntelliJ IDEA something like:
```php
$handler->setEditor(function(string $file, int $line) {
    $file = str_replace("/remote/site/path", "/local/site/path", $file);
    return "idea://open?file=$file&line=$line";
});
```

This works great as long as every developer in a team uses the same editor. Otherwise, one would have to reimplement this for [each and every supported editor](https://github.com/filp/whoops/blob/master/docs/Open%20Files%20In%20An%20Editor.md).

**Comment by denis-sokolov** [comment]
The default editor options are a convenience, but ultimately a complex setup like yours warrants your own editor configuration, like in your comment example. There is no reason to believe file remapping makes sense for all existing and future editors.

Your concern about the team needing to use the same editor applies the same way to situations without remapping in the first place. The usual solution is to call setEditor conditionally.

**Comment by ddanielou** [comment]
Gotcha. That said, our setup is not that complex or unusual: we simply use docker.

Thanks for your answer and for the great software, though!
