### ISSUE TITLE
Blacklisting does not honor multidimensional arrays

### ISSUE THREAD

**Issue by SvenRtbg** [filp/whoops#494]
The fix applied during issue #481 (with PR #482) will only work if the superglobal variables are one-dimensional. The intended fix was for `$_SERVER`'s PHP_AUTH_PW key, and it works for this case. Good thing.

Having sensitive values inside `$_SESSION` is a different story. What's your opinion about this? It would be great if an application could mask arbitrary array key paths. However this will make the interface a little bit more complicated, as well as the code doing the masking. Fortunately, calls to the mask function should be rare.

My current approach is to completely avoid dumping `$_SESSION`, but this requires a code patch as well, so it is sub optimal.

**Comment by mihaeu** [comment]
I actually had the same problem and just ignored it by forking. This would be awesome.

**Comment by denis-sokolov** [comment]
Sounds like a good feature. I would definitely accept a PR that would modify the blacklisting API.
Currently the API is `blacklist('_SESSION', 'key')`. I see the addition as `blacklistNested('_SESSION', 'key/subkey/subsubkey')`. This and the [function `masked`](https://github.com/filp/whoops/blob/master/src/Whoops/Handler/PrettyPageHandler.php#L667) would need a slight modification.

I have added the feature to the [list of possible feature to add](https://github.com/filp/whoops/wiki/Possible-features-to-add). Thank you for the suggestion.

**Comment by SvenRtbg** [comment]
Reading [your comment](https://github.com/filp/whoops/pull/281#issuecomment-100309417) linked from that feature page makes me wonder if you changed your mind on security features (because the one I am about to add to was merged), or if that old comment is specifically targeted at the PRs from the old days.

**Comment by denis-sokolov** [comment]
My decision to accept the feature changed entirely around. But my opinion on the feature didn’t. What changed is the situation Whoops is in.

Strong design needs work. For a strong design, you keep anything that is not perfect, out. To compensate, you provide alternatives, you educate people on the better solutions, you design something better. Today, in 2017, we have no ability to put this extra work in. There is no strong design leader, no strong main use case. Because of that, Whoops is a flexible tool for the users to do what they will with it, and from this point of view, the bar for inclusion is much lower.

@SvenRtbg, this was a great find, thank you!

**Comment by kktsvetkov** [comment]
I've taken a different approach to masking sensitive data with this package, [Fuko\Masked](https://github.com/fuko-php/masked): you "declare" all the passwords and tokens and sensitive data you have and then all of that will be redacted out of any variables you pass. In this way you do not have to worry where your passwords might pop up in any of the dumps you create, no matter how deep they might be in nested sub-arrays or just in some text dumps. I'll appreciate the feedback
