### ISSUE TITLE
Filter frames issue

### ISSUE THREAD

**Issue by DarthSaracen** [filp/whoops#550]
There are troubles when attempt to exclude some traces via filter() method in FrameCollection class.
private $frames' keys have gaps after array_filter() applied, so that may cause such errors as $frames->offsetGet(0)->isApplication() one, because there are no more frame with offset "0". I've temporary used that workaround `$frames->prependFrames([]);` after filter() applied, and it's working now, but I suppose that it's better to automatically reset the keys after filtering.

**Comment by staabm** [comment]
please provide repro code to make your problem more clear.

**Comment by DarthSaracen** [comment]
I'm using following code to filter "bad" frames:

`$handler->setInspector(new class ($exception) extends Inspector {

			public function getFrames() {
				$frames = parent::getFrames()->filter(function(Frame $error) {
					return
						$error->getClass() !== \Core\ErrorHandler::class
						&& strpos($error->getFile(), 'ErrorHandler') === false;
				});
                                // hack
				$frames->prependFrames([]);
				return $frames;
			}

		});`

**Comment by SvenRtbg** [comment]
It would be more interesting to see your code that throws the error because of the missing index. I have the feeling that you should probably change this instead. 

Accessing a fixed array index that gets removed due to filtering does not sound like the best idea. Did you know that `reset()` not only rewinds an iterator, but also returns the first element?

**Comment by DarthSaracen** [comment]
`$frames->offsetGet(0)->isApplication()` is not my code, it's from Whoops. By resetting keys I meant smth like array_map('array_values', $arr) that just reorder keys from 0 to N so indexes like [3, 4, 5] becomes [0, 1, 2]

**Comment by SvenRtbg** [comment]
Ok, I think I get a better picture of what is going on:

The PrettyPageHandler here https://github.com/filp/whoops/blob/141494232ff7d5c565ce2a9cea2be0958243708c/src/Whoops/Handler/PrettyPageHandler.php#L218 assumes that the frames are zero-indexed, which is not always the case if you inject a filtering inspector object.

I'm not familiar with the internals, but my guess would be that Whoops should be using `reset()` to fetch the first frame instead of abusing `count()` (which returns the number of elements, not anything related to their indexes) and then blindly accessing the zero'th element.

**Comment by denis-sokolov** [comment]
Thanks, @DarthSaracen! Fixed in 2.1.14.
