### ISSUE TITLE
Feature Request: Allow manipulation of the file path for the editor url

### ISSUE THREAD

**Issue by MCStreetguy** [filp/whoops#583]
I currently develop an application relying on this really awesome library.
I use a Docker setup for development running a webserver and a database.
Now I tried to set the application root path for the `PrettyPageHandler`, expecting it to be used in the editor href.
The link href still contains the filepath from within the dockerbox, even if the root path has been set to the actual path on my computer.

Am I missunderstanding the meaning of the application root path?
And would it be possible to allow for manipulating the linked file path?

Thanks in advance for your participation and especially in general for making debugging that easy.

**Comment by llevering** [comment]
I develop with Laravel and Whoops is included. And had the same issue. It took me some time, but I was able to get it working with Laravel. I will share what I did and hope you can use it for your environment as well.

For it to work the 'getFile()' function from Frame object needs return the path on host machine, instead of the path in the docker container. The Docker path has to be replaced with the (relative) path of the host machine. I but them in two variables $replacePath and $targetPath, which in turn get their values from the config file in Laravel and in the end even from an environment variable (but that is a bit beyond scope). The frames (which in the contain the filename we need to change) are loaded via the function 'getExceptionFrames()' in the PrettyPageHandler. So I made my own DockerPrettyPageHandler, to be able to alternate the frames that this function returns. Sadly though the Frame object stores the filepath in an array that is basically immutable. So what I do is get the raw date ('getRawFrame()') from the frame and do the path replace and than re-create a FrameCollection with the new data and restore some logic that detects whether a frame is an application or a framework frame.

In code DockerPrettyPageHandler() looks like:
`<?php

namespace App\Exceptions;

use Whoops\Exception\FrameCollection;
use Whoops\Handler\PrettyPageHandler;

class DockerPrettyPageHandler extends PrettyPageHandler
{

    /**
     * Get the stack trace frames of the exception that is currently being handled.
     *
     * @return \Whoops\Exception\FrameCollection;
     */
    protected function getExceptionFrames()
    {
        $frames = $this->getInspector()->getFrames();

        $newFrames = [];

        $applicationFrames = [];

        if ($this->getApplicationPaths()) {
            foreach ($frames as $key => $frame) {
                foreach ($this->getApplicationPaths() as $path) {
                    if (strpos($frame->getFile(), $path) === 0) {
                        $applicationFrames[] = $key;
                        break;
                    }
                }

                $rawFrame = $frame->getRawFrame();
                $rawFrame['file'] = $this->rewriteDockerToLocalPath($rawFrame["file"]);

                $newFrames[] = $rawFrame;
            }
        }

        $newFrameCollection = new FrameCollection($newFrames);
        foreach($newFrameCollection as $key => $frame)
        {
            if(!in_array($key, $applicationFrames))
                continue;

            $frame->setApplication(true);
        }

        return $newFrameCollection;
    }

    protected function rewriteDockerToLocalPaths($paths)
    {
        foreach($paths as $key => &$path)
        {
            $path = $this->rewriteDockerToLocalPath($path);
        }

        return $paths;
    }

    protected function rewriteDockerToLocalPath($path)
    {
        $replacePath = config("app.development_docker_base_path");
        $targetPath = config("app.development_machine_path");

        return str_replace($replacePath, $targetPath, $path);
    }
}`

In Laravel the Exception handler as a function 'whoopsHandler', this function instantiates the Whoops PrettyPageHandler. We need to override that function and make only one change 'new PrettyPageHandler' becomes 'new DockerPrettyPageHandler'. And then we can open our php files with errors in our favorite editor.

**Comment by denis-sokolov** [comment]
This is an advanced feature that I expect will see little use. Still, I would be open for a well-designed PR for it.
