### ISSUE TITLE
"Xdebug helper" Chrome extention: xDebug console.log stopped displaying after adding "Whoops" to my app

### ISSUE THREAD

**Issue by hAtul89** [filp/whoops#613]
I have this example code: 

```
<?php
require __DIR__ . '/vendor/autoload.php';

$whoops = new Whoops\Run;
$handler = new Whoops\Handler\PrettyPageHandler;
$whoops->pushHandler($handler);
$whoops->register(); 

potato(); 
```
xdebug used to display apps error in the browser console (using a Chrome Extension named "Xdebug helper"), and whenever I added whoops to my app, I stopped getting the logs there. 

Any idea how to resolve this? Is it possible to resolve this at all?

**Comment by kktsvetkov** [comment]
Perhaps Whoops error handler replaces the previously registered xdebug error handler. There are some options to call all the handlers using [set_error_handler()](http://php.net/manual/en/function.set-error-handler.php) and [restore_error_handler()](http://php.net/manual/en/function.restore-error-handler.php).

**Comment by SvenRtbg** [comment]
@hAtul89 What would your demo code look like when Xdebug works like expected? I did a quick search to find a magic "xdebug console log" feature, but found nothing, so it might be that enabling this requires additional PHP code.

In general, I'd argue that there can be only one useful default handler for exceptions and errors. It may be possible to detect if some handler has been registered when registering another one, and make this new one call the existing handler afterwards, but this isn't as straightforward and painless as with adding multiple autoloaders, for example, because exception/error handlers will probably deal with the error situation without having additional error handlers in mind, e.g. they may simply call `die()` at the end of their code.

**Comment by hAtul89** [comment]
> @hAtul89 What would your demo code look like when Xdebug works like expected? I did a quick search to find a magic "xdebug console log" feature, but found nothing, so it might be that enabling this requires additional PHP code.
> 
> In general, I'd argue that there can be only one useful default handler for exceptions and errors. It may be possible to detect if some handler has been registered when registering another one, and make this new one call the existing handler afterwards, but this isn't as straightforward and painless as with adding multiple autoloaders, for example, because exception/error handlers will probably deal with the error situation without having additional error handlers in mind, e.g. they may simply call `die()` at the end of their code.

You made me doubt myself and googled it, seems like you were right. 
The logs are actually set by a Chrome Extension named "Xdebug helper" (I feel a bit silly now). 
Sorry I'll edit my main post.

**Comment by SvenRtbg** [comment]
Coming back to this issue after some time, I re-read your edited post.

> Any idea how to resolve this? Is it possible to resolve this at all?

It's not possible, as I tried to suggest in my earlier response.

**Comment by denis-sokolov** [comment]
Sorry about the incompatibility, but it does not seem to be easily resolvable.
