### ISSUE TITLE
custom tab with list of table

### ISSUE THREAD

**Issue by xcl3721** [filp/whoops#637]
hi ,can i add an tab with list of table ?
i'd like use this for SQL list and Loaded File List
and An Tab for special long string 

on pretty error handle

eg:
   $whoops->addMultiColumTable("table1",[["sql","param","cost"],[[$sql,$param1,$cost1],[$sql,$param1,$cost1]]])

**Comment by denis-sokolov** [comment]
This seems to be a support request, a not a bug report or functionality discussion. Unfortunately, we can’t help with that, so consider other avenues: Stack Overflow, forums, and chats. This GitHub issue tracker is most often used specifically about the changes to the project itself.

**Comment by denis-sokolov** [comment]
_(First incorrectly marked this as a support request)_

If I understand correctly, you are asking whether we could add the support of multi-column tables to our addDataTable method in PrettyPageHandler.

Although we don’t have it as explicit functionality right now, you can achieve most of it by putting the entire list of SQL requests into the value of our existing addDataTable:

```php
$handler->addDataTable('Performance', [
    'SQL queries' => [
      ['SQL' => 'SELECT * from things', 'cost' => '0.002s'],
      ['SQL' => 'SELECT * from otherthings where id = ?', 'params' => [19], 'cost' => '0.009s'],
    ],
]);
```

It does not look perfectly aesthetically pleasing, but you can still navigate it, and a good side effect is the amount of SQL queries will not overwhelm the page, since they’ll be collapsed by default.

<img width="619" alt="1" src="https://user-images.githubusercontent.com/113721/62109102-4996fc80-b2b4-11e9-9571-c5f40d70eef1.png">

This is not a highly requested feature, so while I wouldn’t be against including it, it has a low priority on the backlog.

Thanks for suggesting!

**Comment by xcl3721** [comment]
and php://output for php warning notice
